### ISSUE TITLE
Encountered issues running flutter run on macOS (M1 chip)

### ISSUE THREAD

**Issue by hoslo** [cunarist/rinf#110]
```shell
flutter pub add rust_in_flutter

dart run rust_in_flutter template

flutter run
```
After these three commands, i got this error

```shell
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            1.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/z1/7zts17kx6jggkvmjn2wzpnwdw4zzb4/T/flutter_tools.CT3yeo/flutter_ios_build_temp_dirgLf6YD/temporary_xcresult_bundle

    /Users/shuai_yang/Projects/tally/ios/Pods/../.symlinks/plugins/rust_in_flutter/ios/../connectors/cargokit/build_pod.sh: line 2: set: -:
    invalid option
    set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    /Users/shuai_yang/Projects/tally/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set
    to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FMDB' from project 'Pods')
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency
    analysis" is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency
    analysis" is unchecked. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
        /var/folders/z1/7zts17kx6jggkvmjn2wzpnwdw4zzb4/T/flutter_tools.CT3yeo/flutter_ios_build_temp_dirgLf6YD/temporary_xcresult_bundle


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

**Comment by bookshiyi** [comment]
> ```shell
> flutter pub add rust_in_flutter
> 
> dart run rust_in_flutter template
> 
> flutter run
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> After these three commands, i got this error
> ```shell
> Launching lib/main.dart on iPhone 14 Pro in debug mode...
> Running Xcode build...                                                  
> Xcode build done.                                            1.1s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     Writing result bundle at path:
>         /var/folders/z1/7zts17kx6jggkvmjn2wzpnwdw4zzb4/T/flutter_tools.CT3yeo/flutter_ios_build_temp_dirgLf6YD/temporary_xcresult_bundle
> 
>     /Users/shuai_yang/Projects/tally/ios/Pods/../.symlinks/plugins/rust_in_flutter/ios/../connectors/cargokit/build_pod.sh: line 2: set: -:
>     invalid option
>     set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
>     Command PhaseScriptExecution failed with a nonzero exit code
>     note: Building targets in dependency order
>     /Users/shuai_yang/Projects/tally/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set
>     to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FMDB' from project 'Pods')
>     note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency
>     analysis" is unchecked. (in target 'Runner' from project 'Runner')
>     note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency
>     analysis" is unchecked. (in target 'Runner' from project 'Runner')
> 
>     Result bundle written to path:
>         /var/folders/z1/7zts17kx6jggkvmjn2wzpnwdw4zzb4/T/flutter_tools.CT3yeo/flutter_ios_build_temp_dirgLf6YD/temporary_xcresult_bundle
> 
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 14 Pro.
> ```

Maybe you could try commenting out the line with the code `set -e` in the file `connectors/cargokit/build_pods.sh`, then attempt to build again and pay attention to the logs.

**Comment by hoslo** [comment]
> > ```shell
> > flutter pub add rust_in_flutter
> > 
> > dart run rust_in_flutter template
> > 
> > flutter run
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After these three commands, i got this error
> > ```shell
> > Launching lib/main.dart on iPhone 14 Pro in debug mode...
> > Running Xcode build...                                                  
> > Xcode build done.                                            1.1s
> > Failed to build iOS app
> > Error output from Xcode build:
> > ↳
> >     ** BUILD FAILED **
> > 
> > 
> > Xcode's output:
> > ↳
> >     Writing result bundle at path:
> >         /var/folders/z1/7zts17kx6jggkvmjn2wzpnwdw4zzb4/T/flutter_tools.CT3yeo/flutter_ios_build_temp_dirgLf6YD/temporary_xcresult_bundle
> > 
> >     /Users/shuai_yang/Projects/tally/ios/Pods/../.symlinks/plugins/rust_in_flutter/ios/../connectors/cargokit/build_pod.sh: line 2: set: -:
> >     invalid option
> >     set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
> >     Command PhaseScriptExecution failed with a nonzero exit code
> >     note: Building targets in dependency order
> >     /Users/shuai_yang/Projects/tally/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set
> >     to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FMDB' from project 'Pods')
> >     note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency
> >     analysis" is unchecked. (in target 'Runner' from project 'Runner')
> >     note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency
> >     analysis" is unchecked. (in target 'Runner' from project 'Runner')
> > 
> >     Result bundle written to path:
> >         /var/folders/z1/7zts17kx6jggkvmjn2wzpnwdw4zzb4/T/flutter_tools.CT3yeo/flutter_ios_build_temp_dirgLf6YD/temporary_xcresult_bundle
> > 
> > 
> > Could not build the application for the simulator.
> > Error launching application on iPhone 14 Pro.
> > ```
> 
> Maybe you could try commenting out the line with the code `set -e` in the file `connectors/cargokit/build_pods.sh`, then attempt to build again and pay attention to the logs.

I commented out `set-e`, log changed to this
```shell
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            1.8s
Failed to build iOS app
Error (Xcode): File not found: /Users/shuai_yang/Projects/tally/build/ios/Debug-iphonesimulator/rust_in_flutter/libhub.a


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

**Comment by bookshiyi** [comment]
```
  Launching lib/main.dart on iPhone 14 Pro in debug mode...
  Running Xcode build...                                                  
  Xcode build done.                                            1.8s
  Failed to build iOS app
  Error (Xcode): File not found: /Users/shuai_yang/Projects/tally/build/ios/Debug-iphonesimulator/rust_in_flutter/libhub.a
  
  
  Could not build the application for the simulator.
  Error launching application on iPhone 14 Pro.
```

It seem like that rust code compilation not correct, or check the path of `libhub.a` if exist or not.

**Comment by hoslo** [comment]
> libhub.a

libhub.a not exist

**Comment by bookshiyi** [comment]
> > libhub.a
> 
> libhub.a not exist

Could you post more logs about that compilation of rust?

**Comment by temeddix** [comment]
Also, can you check if the example app inside `/example` of this repository works well on your machine?

On Intel mac, it runs well:
<img width="543" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/f5101ce1-36b0-40eb-9938-8d0411c855b5">

**Comment by hoslo** [comment]
> Also, can you check if the example app inside `/example` of this repository works well on your machine?

This is the output of example running `flutter run` :
```shell
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            2.7s
Failed to build iOS app
Error (Xcode): cannot find macro `stringify` in this scope


Error (Xcode): cannot find attribute `derive` in this scope


Error (Xcode): could not compile `cfg-if` (lib) due to 2 previous errors


Error (Xcode): could not compile `scopeguard` (lib) due to 16 previous errors


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

**Comment by temeddix** [comment]
Not really relevant, but I do understand that why CI didn't catch this problem. It was basically because GitHub CI's `macos-latest` is based on Intel machine.

It seems we should figure out on real M1 macs(pity that I don't have one)..

**Comment by hoslo** [comment]
> Not really relevant, but I do understand that why CI didn't catch this problem. It was basically because GitHub CI's `macos-latest` is based on Intel machine.
> 
> It seems we should figure out on real M1 macs(pity that I don't have one)..

The real mistake is 
```shell
Error (Xcode): File not found: /Users/shuai_yang/Projects/tally/build/ios/Debug-iphonesimulator/rust_in_flutter/libhub.a
```
Is there anything I can help rule out? Or is there a clue?

**Comment by bookshiyi** [comment]
<img width="326" alt="Screenshot 2023-08-23 at 19 10 48" src="https://github.com/cunarist/rust-in-flutter/assets/14087838/b3186347-76fd-4009-9c37-341ea773eb74">

Apple Silicon(arm64) version , the `example` run well.

**Comment by bookshiyi** [comment]
> > Not really relevant, but I do understand that why CI didn't catch this problem. It was basically because GitHub CI's `macos-latest` is based on Intel machine.
> > It seems we should figure out on real M1 macs(pity that I don't have one)..
> 
> The real mistake is
> 
> ```shell
> Error (Xcode): File not found: /Users/shuai_yang/Projects/tally/build/ios/Debug-iphonesimulator/rust_in_flutter/libhub.a
> ```
> 
> Is there anything I can help rule out? Or is there a clue?

Maybe try to run `flutter clean` before  `flutter run` is a possible way.
Or attempt to run the example directly.
Or attempt to upgrade toolchains such as Xcode, rust, dart to latest version?

**Comment by temeddix** [comment]
Oh, I see that it runs well on iOS with M1 macs. Hope that I can be a help, but since I don't have a machine it's hard for me to provide direct support. Maybe it is problems of toolchains, but I'll try to inspect deeper when I have time :)

**Comment by hoslo** [comment]
> Oh, I see that it runs well on iOS with M1 macs. Hope that I can be a help, but since I don't have a machine it's hard for me to provide direct support. Maybe it is problems of toolchains, but I'll try to inspect deeper when I have time :)

example works just fine，moreover i replace example/ios/.symlinks directory to my project also work fine,So what's the problem?

**Comment by hoslo** [comment]
> > Oh, I see that it runs well on iOS with M1 macs. Hope that I can be a help, but since I don't have a machine it's hard for me to provide direct support. Maybe it is problems of toolchains, but I'll try to inspect deeper when I have time :)
> 
> example works just fine，moreover i replace example/ios/.symlinks directory to my project also work fine,So what's the problem?

Another discovery is that I can use cargo lipo, then copy libhub.a to build/Debug-iphonesimulator/rust_in_flutter is also ok

**Comment by temeddix** [comment]
Maybe this is related to #83. This seems to be a behavior of cargokit under the hood, hmm

**Comment by wheregmis** [comment]
Try this for m1 Mac.
`cd macos`
`pod install`

same for iOS. Works for me.

**Comment by temeddix** [comment]
Should we write this workaround in the docs?

**Comment by Alphapage** [comment]
I have the same error: it was working once, then failed !!!
I switched to version 4.8.0 or 4.8.2 in pubspec.yaml, but not 4.9.0 because I only get black screen.
It seems to be an EOL problem in build_poc.sh, but I haven't investigated...

**Comment by temeddix** [comment]
Hi @Alphapage , thank you for the report :)

Would you mind sharing your console output with us here? Maybe there can be information about what is causing the error.

**Comment by temeddix** [comment]
t

**Comment by Alphapage** [comment]
No problem, @temeddix .
I get the same error that @hoslo describes from his first post:
```
./cargokit/build_pod.sh: line 2: set: -e
: invalid option

set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by Alphapage** [comment]
Just for info, I replaced build_pod.sh and run_build_tool.sh by 4.8.2 version and now, 4.10.0 is working.

**Comment by temeddix** [comment]
@Alphapage 

Version 4.11.1 has removed trailing blank lines from `.sh` files just like you mentioned. Could you try it out and share the result?

**Comment by Alphapage** [comment]
Sorry: same error !

**Comment by Alphapage** [comment]
You mean you formatted to unix because it was generated from Windows ?
I thought this was the problem. Sorry

**Comment by temeddix** [comment]
Oh, I think I misunderstood your solution. I remove the 'last line' from those file. I will convert CRLF to LF and publish 4.11.2 again.

I've published 4.10 and 4.11 on Windows, where the files were written in CRLF. I will publish 4.11.2 on macOS to avoid those issues.

**Comment by temeddix** [comment]
Verion 4.11.2 is published with LF EOL, not CRLF EOL, unlike 4.11.1

Could you share the result after you try it out?

P.S. It's a strange thing that 4.11.1 with CRLF EOL works on my intel mac, hmm...

**Comment by Alphapage** [comment]
Works perfectly now 👍 
Congratulations and many thanks

**Comment by temeddix** [comment]
Happy to hear that:) Good luck with your project, and feel free to come back if you have any other issues or ideas!
