### ISSUE TITLE
Protobuf Implementation

### ISSUE THREAD

**Issue by wheregmis** [cunarist/rinf#118]
I did saw a protobuf implementation issue a while ago. I don't know if its still the scope of the project or not. Not much of a rust or flutter developer but I do have it implemented already. If its still the scope of the project I would love to create a pr for protobuf implementation instead of a messagepack. (I am on a mac m1 so I cant test on mac or windows but I can verify it works well with android, ios and web)

**Comment by bookshiyi** [comment]
So exciting.

The original issue was #106, which has now been moved to the project without canceling this plan.You could found it at [Goals](https://github.com/orgs/cunarist/projects/2/views/1?pane=issue&itemId=36845225).

You can submit PR, and the GitHub actions program will automatically check the compilation on different platforms.

**Comment by temeddix** [comment]
Hi @wheregmis , thank you for your kind suggestion about the PR. I could say that this issues is the objective for 3.0.

If you do make a PR, I will participate in polishing the template and automating installations, as well as testing on various platforms. Again, we would be happy to see a helping hand :)

**Comment by wheregmis** [comment]
I do can cleanup few stuffs, but let me submit a pr with the commit which is working. And we can polish the readme and other stuffs till 3.0.

**Comment by temeddix** [comment]
As @bookshiyi mentioned, the description of this goal is at: https://github.com/orgs/cunarist/projects/2?pane=issue&itemId=36845225

**Comment by bookshiyi** [comment]
I'm happy to support test on windows Linux macOS(arm64).
