### ISSUE TITLE
Building apk requires rust stable toolchain stable-x86_64-pc-windows-msvc and doesn't work with nightly

### ISSUE THREAD

**Issue by ryanhossain9797** [cunarist/rinf#147]
It seems building for android fails if the stable windows toolchain is not installed.

# Steps to reproduce

## Setup everything but install rustup nightly only
```
> flutter build apk
C:\Users\raiyan.hossain\.cargo\bin\rustup.exe
error: toolchain 'stable-x86_64-pc-windows-msvc' is not installed

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\<UserName>\AppData\Local\Pub\Cache\hosted\pub.dev\rust_in_flutter-3.7.3\cargokit\gradle\plugin.gradle' line: 57

* What went wrong:
Execution failed for task ':rust_in_flutter:cargokitCargoBuildHubRelease'.
> Process 'command 'C:\Users\<UserName>\AppData\Local\Pub\Cache\hosted\pub.dev\rust_in_flutter-3.7.3\cargokit\gradle\..\run_rust_tool.cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleRelease'...                         2,822ms
Gradle task assembleRelease failed with exit code 1
NativeCommandExitException: Program "flutter.bat" ended with non-zero exit code: 1.
```

## Switch to stable and try again
```
> rustup default stable
...
> flutter build apk
SUCCESSS
```

## Switch to nightly and try again
```
> rustup default nightly
...
> flutter build apk
SUCCESS still works because the stable toolchain is still present even though it's not default?
```

## Remove stable and try again
```
> rustup toolchain remove stable
...
> flutter build apk
FAILURE same as before
```

# System Information
```
> rustc --version
rustc 1.74.0-nightly (8142a319e 2023-09-13)

> protoc --version
libprotoc 24.2

> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.4, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

**Comment by temeddix** [comment]
Thanks for the report, we will inspect this as soon as possible.

P.S. Please include the system information as guided when leaving an issue :)

**Comment by ryanhossain9797** [comment]
> Thanks for the report, we will inspect this as soon as possible.
> 
> P.S. Please include the system information as guided when leaving an issue :)

Thanks

Sorry I didn't include the system information. I was on mobile. I've updated the issue with steps to reproduce and system info.

**Comment by temeddix** [comment]
Looks like it was a problem with `cargokit`, the connector between Flutter and Rust. Can you try the newly published version 3.7.4 with newer `cargokit` and check if the issue remains? I'm not sure yet if this will fully solve the issue :\

**Comment by ryanhossain9797** [comment]
It looked like it was installing stable as needed.
```
...
Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
INFO: Precompiled binaries are disabled
INFO: Installing Rust toolchain: stable
Running Gradle task 'assembleRelease'...
...
```

But then its started failing with hundreds of errors like this
```
SEVERE: error[E0463]: can't find crate for `std`
SEVERE:    --> C:\Users\raiyan.hossain\.cargo\registry\src\index.crates.io-6f17d22bba15001f\anstyle-1.0.3\src\style.rs:137:68
SEVERE:     |
SEVERE: 137 |     pub fn write_reset_to(self, write: &mut dyn std::io::Write) -> std::io::Result<()> {
SEVERE:     |                                                                    ^^^ can't find crate
SEVERE:     |
SEVERE:     = note: the `armv7-linux-androideabi` target may not be installed
SEVERE:     = help: consider downloading the target with `rustup target add armv7-linux-androideabi`
```

Switching back to stable seems to work fine.

The only thing I've changed is `rust_in_flutter: ^3.7.4`

**Comment by temeddix** [comment]
Hmm, I wonder why... can you try running this before building in the CLI?

```bash
rustup target add armv7-linux-androideabi
```

**Comment by ryanhossain9797** [comment]
Ok so I couldn't reproduce the issue. I ran `rustup self uninstall` to remove rust entirely and install nightly from scratch. `flutter build apk` seemed to work fine. I'm willing to consider this resolved.

**Comment by temeddix** [comment]
Yeah, to me it looks like some nightly target of Rust was missing. Maybe it is safe to consider this as resolved :)

**Comment by ryanhossain9797** [comment]
That being said, Ideally wouldn't we want to build it using nightly? What if the rust end needs to use a nightly feature?

**Comment by temeddix** [comment]
Oh, I understood that your problem was resolved in nightly. Then we should investigate further into this issue, yes. Let's keep this issue open and discuss it further.

**Comment by temeddix** [comment]
That problem seems to arise from `cargokit`, so ideally we should inspect the repository over there. To be honest, I'm not so free of time these days, so whoever finds out the cause should perhaps leave a PR there when we find out the problem.

https://github.com/irondash/cargokit

**Comment by temeddix** [comment]
By the way, does simply running `cargo build` work?

**Comment by ryanhossain9797** [comment]
yeah, cargo build works.

The issue is fixed in the sense that now it automatically sets up and uses `stable` to build without erroring out or changing the default.

I can see that after building the app with `flutter build apk` I have both. But I only had nightly before. So the build process itself installed and used stable.
```
> rustup toolchain list
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)
```

So while I don't need to explicitly install and default stable for the build to work, It's still building rust with stable.. not nightly.

**Comment by ryanhossain9797** [comment]
Looks like they've merged some changes on their end

https://github.com/irondash/cargokit/issues/25

**Comment by knopp** [comment]
> Looks like they've merged some changes on their end
> 
> [irondash/cargokit#25](https://github.com/irondash/cargokit/issues/25)

After the change cargokit should properly install targets for the toolchain that will be used to build the crate instead of default toolchain. If your plugin crate needs to be built with specific toolchain you can configure it through `cargokit.yaml`, see for example [here](https://github.com/superlistapp/super_native_extensions/blob/main/super_native_extensions/rust/cargokit.yaml).

**Comment by temeddix** [comment]
Great! I will merge this change soon. Thank you for your help :)

**Comment by temeddix** [comment]
Version 4.0.0 has this new cargokit. Can you try it and tell us if the issue remains?

**Comment by ryanhossain9797** [comment]
@temeddix think the template command broke on windows 😅
I can't run `rifs template` on a fresh flutter project. there's double //. on 4.0.2
```
FileSystemException: Creation failed, path = '/path/to/app/native//hub' (OS Error: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by temeddix** [comment]
Oh, I will fix this in an hour. Thanks for telling us!

**Comment by temeddix** [comment]
It took some time to fix this, now `rifs template` will work well on Windows with RIF 4.0.3. Would you mind verifying if the new version works properly?

**Comment by ryanhossain9797** [comment]
@temeddix I've verified the template works

Will get back to you on the original issue of nightly targets

**Comment by ryanhossain9797** [comment]
So setting up nightly in the cargokit.yaml for the hub crate as @knopp suggested seems to do the trick

```yaml
cargo:
  release:
    toolchain: nightly
```

Perhaps you could consider making it part of the template?

**Comment by temeddix** [comment]
Maybe including `cargokit.yaml` in the template will be a bit overkill because most of the people will use Rust stable, but I can write the exact process to use nightly Rust in the docs.

Thank you for the valuable info :)

**Comment by ryanhossain9797** [comment]
Yes thank you. docs should be sufficient.
