### ISSUE TITLE
Demo is not working on Firefox and Safari

### ISSUE THREAD

**Issue by temeddix** [cunarist/rinf#164]
## Report

`rif-example.cunarist.com` doesn't seem to work on Firefox and Safari. Maybe it's a HTTPS certificate problem, but we need to inspect deeper. It works well on Chrome and Edge.

## Steps to Reproduce

Open the website with Firefox or Safari.

## System Information

Not relevant.

```bash
rustc --version
protoc --version
flutter doctor
```

**Comment by dcorbe** [comment]
Not exactly "cross platform" if it doesn't support an entire class of browsers.   What a shame.

**Comment by temeddix** [comment]
With RIF 4.3.0 the command `flutter run` and the demo website `rif-example.cunarist.com` works well on all browsers.

**Comment by temeddix** [comment]
This was mainly because `cross-origin-embeder-policy: credentialless` HTTP header doesn't work in Safari and Firefox, while it works in Chrome and Edge. Now RIF uses `cross-origin-embeder-policy: require-corp`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy
