### ISSUE TITLE
MacOS build failed with specific crate

### ISSUE THREAD

**Issue by htoopyaelinn56** [cunarist/rinf#171]
Thank for the great package. I encountered build failed problem in macOS with [machineid-rs](https://crates.io/crates/machineid-rs) crate. The project does not build failed if I don't import that crate. As I import this crate,  I encountered a build failed problem with the following error. 
<img width="1061" alt="Screenshot 2023-09-26 at 07 18 12" src="https://github.com/cunarist/rust-in-flutter/assets/85918337/d346d31c-267e-429b-9563-396541e4a1ba">

My flutter, rust and protoc versions
<img width="547" alt="Screenshot 2023-09-26 at 07 18 54" src="https://github.com/cunarist/rust-in-flutter/assets/85918337/682ecd1e-f482-4a70-85fd-4ce733b7a53f">

I use latest version of [machineid-rs](https://crates.io/crates/machineid-rs). I did rifs template, rifs message. Did I miss something to do for external crates.

**Comment by bookshiyi** [comment]
It is seem like similar to issues #83 and #110 

@htoopyaelinn56 Is it an arm Mac?

**Comment by temeddix** [comment]
Yeah it is, looks like we need to inspect this problem.

**Comment by temeddix** [comment]
Hmm, `machineid-rs` looks like a pure Rust crate. No C code is included. I wonder if `crate-type` in `Cargo.toml` can be the cause.

I will try to fix this, but I might be busy for a while because of my own schedules. Please leave a PR if anyone finds a good solution 😶

**Comment by htoopyaelinn56** [comment]
@bookshiyi yes it is arm.

**Comment by temeddix** [comment]
I wonder, is it possible to check if the app runs on Windows or Linux?

**Comment by htoopyaelinn56** [comment]
Sorry I don't have one but it do run on android.

**Comment by temeddix** [comment]
Oh, can you share the result on Android? 🙏

**Comment by htoopyaelinn56** [comment]
Sorry my mistake. The package itself does not support android. The app ran when there is no ```machineid-rs``` dependency.

**Comment by temeddix** [comment]
I could reproduce the same error as you wrote on macOS. Still inspecting..

**Comment by temeddix** [comment]
Version 4.5.0 should have fixed this bug. Could you try it out?

**Comment by htoopyaelinn56** [comment]
Thanks, it compiles now.

**Comment by temeddix** [comment]
Happy to hear that :) feel free to come back if you have other issues
