### ISSUE TITLE
Could not find file `rinf`

### ISSUE THREAD

**Issue by jxqu3** [cunarist/rinf#193]
## Report

_Please mention the problem here. If it's not a problem, write it as a discussion._

After installing all components and the rinf cli, I get this error:
```
> rinf
Could not find file `rinf`
```

## Steps to Reproduce

_Please describe the exact steps to reproduce the error._
1. Install Rustup
2. Install Flutter SDK
3. Install Protoc
4. cargo install rinf
5. rinf (or dart run rinf)

## System Information

_Please provide the output from the command below, using markdown codeblock syntax._

```bash
rustc --version
rustc 1.75.0-nightly (475c71da0 2023-10-11) #also happens with stable
protoc --version
libprotoc 24.4
flutter doctor
[✓] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.22621.2428], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
    ! Device emulator-5562 is offline.
[✓] Network resources

• No issues found!
```

**Comment by temeddix** [comment]
Hi @checkm4ted , let me help you with this issue.

This error occurs when the current working directory is not a Flutter project folder, or `rinf` Flutter package is not installed yet. Could you check that you're at Flutter project's directory(where `pubspec.yaml` is located) and run `flutter pub add rinf`?

**Comment by jxqu3** [comment]
My bad, you're right

**Comment by temeddix** [comment]
No problem! feel free to ask here :)

**Comment by stegrams** [comment]
@temeddix I just installed Rinf and it looks promising. Thank you for sharing! 

This answer made me realize allot about the nature of Rinf. 
It would be a great message to have when one run ``rinf --help`` after the ``cargo --install`` as suggested by the "Quick start -> Shorthand Command" documentation. :+1:

**Comment by temeddix** [comment]
@stegrams Thanks for the idea! Indeed, `rinf --help` does not work right after `cargo install rinf`. I will try to organize things a bit :)

**Comment by temeddix** [comment]
Now documentations are organized so that users won't face the same error you've faced :) Thank you so much for reporting!

**Comment by istudyatuni** [comment]
Hi, `rinf --help` still shows an error ``Could not find package `rinf` or file `rinf` `` when running not inside flutter/rinf project
