### ISSUE TITLE
Example Flutter project uses +500% CPU on development env

### ISSUE THREAD

**Issue by mskasal** [cunarist/rinf#209]
## Report

The example Flutter project uses an immense CPU load.

## Steps to Reproduce

1. Clone the repo
2. Run the example Flutter project local

## System Information

```bash
rustc --version
protoc --version
flutter doctor

rustc 1.72.0 (5680fa18f 2023-08-23)
libprotoc 24.3
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] VS Code (version 1.85.0-insider)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```
```bash
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Model Number: Z15G0027BD/A
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
      macOS: 14.0 (23A344)
      System Firmware Version: 10151.1.1
      OS Loader Version: 10151.1.1
```
<img width="317" alt="Screenshot 2023-11-05 at 20 56 53" src="https://github.com/cunarist/rinf/assets/2426680/6e1a22dc-0f76-42e4-aab0-75dc83b6a68f">

**Comment by temeddix** [comment]
Hi @mskasal , thank you for leaving your valuable opinion :)

It's not surprising as that's an intended behavior. What's taking up that CPU load is the *mandelbrot fractal*, which uses heavy calculation to check multicore parallelization, being drawn on the screen 25 frames a second.

If you remove those lines, the CPU usage will go down to the base level:
```diff
// flutter_ffi_plugin/example/native/hub/src/lib.rs

use bridge::respond_to_dart;
use web_alias::*;
use with_request::handle_request;

mod bridge;
mod messages;
mod sample_functions;
mod web_alias;
mod with_request;

/// This `hub` crate is the entry point for the Rust logic.
/// Always use non-blocking async functions such as `tokio::fs::File::open`.
    async fn main() {
        // This is `tokio::sync::mpsc::Reciver` that receives the requests from Dart.
        let mut request_receiver = bridge::get_request_receiver();
        // Repeat `crate::spawn` anywhere in your code
        // if more concurrent tasks are needed.
-       crate::spawn(sample_functions::stream_mandelbrot());
-       crate::spawn(sample_functions::run_debug_tests());
        while let Some(request_unique) = request_receiver.recv().await {
            crate::spawn(async {
                let response_unique = handle_request(request_unique).await;
                respond_to_dart(response_unique);
            });
        }
    }
```

Please note that CPU usage in the 'template'(applied with `rinf template` command) does not go up high like that. If you have any other questions, please let me know!

**Comment by mskasal** [comment]
> Hi @mskasal, thank you for leaving your valuable opinion :)
> 
> It's not surprising as that's an intended behaviour. What's taking up that CPU load is the _mandelbrot fractal_, which uses heavy calculation to check multicore parallelization, being drawn on the screen 25 frames a second.
> 
> If you remove those lines, the CPU usage will go down to the base level:
> 
> ```diff
> // flutter_ffi_plugin/example/native/hub/src/lib.rs
> 
> use bridge::respond_to_dart;
> use web_alias::*;
> use with_request::handle_request;
> 
> mod bridge;
> mod messages;
> mod sample_functions;
> mod web_alias;
> mod with_request;
> 
> /// This `hub` crate is the entry point for the Rust logic.
> /// Always use non-blocking async functions such as `tokio::fs::File::open`.
>     async fn main() {
>         // This is `tokio::sync::mpsc::Reciver` that receives the requests from Dart.
>         let mut request_receiver = bridge::get_request_receiver();
>         // Repeat `crate::spawn` anywhere in your code
>         // if more concurrent tasks are needed.
> -       crate::spawn(sample_functions::stream_mandelbrot());
> -       crate::spawn(sample_functions::run_debug_tests());
>         while let Some(request_unique) = request_receiver.recv().await {
>             crate::spawn(async {
>                 let response_unique = handle_request(request_unique).await;
>                 respond_to_dart(response_unique);
>             });
>         }
>     }
> ```
> 
> Please note that CPU usage in the 'template'(applied with `rinf template` command) does not go up high like that. If you have any other questions, please let me know!

@temeddix 
Thank you for getting back to me, I like your work here. I am learning Rust and a big fan of Flutter.
And `rinf` is an amazing tool that I can experiment with and learn simultaneously. 
🩵❤️
I'm really excited to dive into this topic and learn more as I go. Thanks for inspiring me!

**Comment by temeddix** [comment]
Happy to hear that :) If you have other opinions, feel free to come back later. Also, if you see others seeking for a solution for using Flutter and Rust, please let them know!
