### ISSUE TITLE
Flutter Web CORS error

### ISSUE THREAD

**Issue by ArinFaraj** [cunarist/rinf#214]
There should be a mention in the documentation that we must configure some HTTP headers for flutter web server.

On flutter web by calling `Rinf.ensureInitialized();` it will try to access `hub.js` which fails with CORS errors

After a long search I found this mentioned in [flutter_rust_bridge docs](https://cjycode.com/flutter_rust_bridge/build_wasm.html#setting-up-the-web-server)
So I applied it on my static web server configurations and it worked

This is my example Dockerfile and server configs

<details>
<summary>Dockerfile</summary>

FROM rust:1.73 as builder
RUN rustup toolchain install nightly
RUN rustup +nightly component add rust-src
RUN rustup +nightly target add wasm32-unknown-unknown
RUN rustup target add wasm32-unknown-unknown
RUN cargo install wasm-pack
RUN cargo install wasm-bindgen-cli
RUN cargo install protoc-gen-prost

RUN apt-get update
RUN apt-get install -y curl git unzip protobuf-compiler

RUN cargo install rinf

ARG FLUTTER_SDK=/usr/local/flutter
ARG FLUTTER_VERSION=3.13.9

RUN git clone -b 3.13.9 https://github.com/flutter/flutter.git $FLUTTER_SDK
RUN cd $FLUTTER_SDK && git fetch && git checkout $FLUTTER_VERSION

ENV PATH="$FLUTTER_SDK/bin:$FLUTTER_SDK/bin/cache/dart-sdk/bin:${PATH}"

RUN flutter doctor -v

ARG APP=/app/
WORKDIR $APP

COPY pubspec.* ./
COPY assets/ ./assets/

RUN flutter pub get

COPY messages/ ./messages/
COPY native $APP/native
RUN rinf message
RUN rinf wasm --release

COPY web $APP/web
COPY lib $APP/lib

RUN flutter build web

FROM joseluisq/static-web-server:2

COPY server_config.toml /config.toml
COPY --from=builder /app/build/web /public/

ENV SERVER_CONFIG_FILE=/config.toml

EXPOSE 3000

</details>

<details>

<summary>server_config.toml</summary>

[advanced]
security-headers = true
[[advanced.headers]]
source = "*"
[advanced.headers.headers]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

</details>

**Comment by temeddix** [comment]
Hi @ArinFaraj , thank you for your valuable feedback :)

Actually, there is a mention about CORS in the FAQ section:

https://rinf-docs.cunarist.com/frequently-asked-questions/#the-built-web-version-shows-errors-related-to-cross-origin-policy-in-the-browser-console

But now I do think putting that info somewhere more findable would be nice. Thanks for the heads-up!

**Comment by temeddix** [comment]
This information was moved here: https://rinf-docs.cunarist.com/running-and-building/

![image](https://github.com/cunarist/rinf/assets/66480156/0fde5b08-e4c9-40f0-8490-a4a23d20c95c)
