### ISSUE TITLE
Response messages being `null` when wating for a long time

### ISSUE THREAD

**Issue by kaimatzu** [cunarist/rinf#221]
Need a way to log and trace the operations from rust side because sometimes I get a null return value in 

```
final responseMessage = RinfInterface.ReadResponse.fromBuffer(
      rustResponse.message!,
);
```

My operations are asynchronous and need to wait a bit before returning data to Flutter. I'm assuming rinf doesn't have a timeout between open connections right? I might be wrong. The documentation doesn't help me too much either.

**Comment by temeddix** [comment]
Hi, @kaimatzu , thanks for the report :)

Did you check this section in the docs? If it's insufficient, please tell me more about your concerns.

- https://rinf-docs.cunarist.com/writing-code/#response-timeout

**Comment by kaimatzu** [comment]
Thank you so much! I probably skimmed through that section due to me being in a rush lol. Although, is there a way to set the response timeout to unlimited? Some of my functions *really* do need to wait for a response however long that may take.

**Comment by temeddix** [comment]
Oh, that was your concern. For now, you can set it to a really long time(maybe a week?), though providing an unlimited response timeout would be nice too. Thanks for the idea! I'll keep this issue open until we implement that feature.

**Comment by kaimatzu** [comment]
On a side note, will there be a plan for adding a logging functionality for rust to the flutter side? It seems like it might be possible to send logs to the vm without closing the connection.

**Comment by temeddix** [comment]
Do you mean something like this?

- https://rinf-docs.cunarist.com/writing-code/#printing-for-debugging

Or, possibly something more?

**Comment by kaimatzu** [comment]
Thank a lot! I'll wait until till you guys implement the no timeout feature. I'll keep posted for the next few updates.
