### ISSUE TITLE
Some apple-sys functions could not work well 

### ISSUE THREAD

**Issue by bookshiyi** [cunarist/rinf#227]
## Steps to Reproduce

Minimal example:

```toml
# ./native/hub/Cargo.toml
...
[dependencies]
apple-sys = { version = "0.2", features = ["CoreWLAN"] }
```

```rust
// ./native/hub/src/lib.rs
...
use apple_sys::CoreWLAN::*;
async fn main() {
    unsafe {
        let current_network = CWWiFiClient::sharedWiFiClient().interface();
        println!("Transmit Rate: {:?}Mbps", current_network.transmitRate());
        println!("RSSI: {:?}dBm", current_network.rssiValue());
        println!("Noise: {:?}dBm", current_network.noiseMeasurement());
    }
...
}

#[tokio::test]
async fn main_test() {
    main().await;
}
```

## Report

Some apple-sys functions could work well standalone (purely rust), and get non-null data from corewlan:

```
cargo test -- --nocapture
```
```
Trasnmit Rate: 433.0Mbps
RSSI: -44dBm
Noise: -88dBm
```

but when the `async fn main()` compiled into flutter, only can get null data from corewlan:
```
flutter run -d macos
```
```
Trasnmit Rate: 0Mbps
RSSI: 0dBm
Noise: 0dBm
```

Maybe its related to the `async fn main()` how be called in the file ./native/hub/src/bridge/interface.rs.

**Comment by temeddix** [comment]
Hmm, maybe this can be a network permission issue on iOS, though I'm not 100% sure.

Could you check if the info at this link solves the problem?

- https://docs.flutter.dev/data-and-backend/networking

**Comment by bookshiyi** [comment]
> Hmm, maybe this can be a network permission issue on iOS, though I'm not 100% sure.
> 
> Could you check if the info at this link solve the problem?
> 
> * https://docs.flutter.dev/data-and-backend/networking

Wow, thanks for your important tips for me.

**Comment by temeddix** [comment]
FYI, this discussion does look similar

- https://github.com/cunarist/rinf/discussions/189#discussioncomment-7366972

**Comment by temeddix** [comment]
Now detailed disucssions that might be related to this issue is at #280 , so I'll be closing this one now. If anyone faces similar problems, please head over to #280.

FYI, this problem was handled in a few pull requests before. Generally speaking, it should be possible to access Apple system now.
