### ISSUE TITLE
`rinf message` won't create `messages` mod if there is no proto files in `messages` root

### ISSUE THREAD

**Issue by ngoquang2708** [cunarist/rinf#248]
If there is no `messages/*.proto` files, run `rinf message` won't generate `messages/mod.rs` for Rust.

**Comment by temeddix** [comment]
Thanks for the report! I will handle this as soon as possible.

**Comment by thlorenz** [comment]
As a workaround I added a `_root.proto` at the root and put the following in there:

```proto
syntax = "proto3";
package _root;

message RootState {bool fake = 1;}
```

And to avoid `unused` warnings on the Rust end I added this line in a module of the hub crate:
```rs
let _ = messages::_root::ID;
```

**Comment by temeddix** [comment]
Everything works fine on Windows, even if there's no proto file in the `messages` root. Could you share which OS you are using?

**Comment by ngoquang2708** [comment]
I'm on Arch Linux.
I've setup a Windows virtual machine. 
Setup a sample Rinf project.
Delete every proto files in ```messages``` root.
Ran ```rinf message```.
Result is no generated ```mod.rs``` for ```messages``` root in Rust. Because of that I cannot refer to it in Rust code, which indicate as red in the attach image.

![Screenshot_20240108_160616](https://github.com/cunarist/rinf/assets/9676278/fbf578bd-cea6-465e-a040-eb157d143014)

**Comment by temeddix** [comment]
Rinf 5.3.1 fixed this issue, so I recommend to try it out :) This problem was mostly due to `rinf message` not awaiting subfolder to be created.

P.S. You need to run `rinf template`, if you're coming from Rinf version 4.
