### ISSUE TITLE
RINF site has bad CA in Brave

### ISSUE THREAD

**Issue by Zk2u** [cunarist/rinf#249]
## Report

RINF example website has a ERR_CERT_AUTHORITY_INVALID error in brave when trying to load the docs

**Comment by temeddix** [comment]
Hi, @617a7a , thanks for the report!

It looks like Brave doesn't trust the certificate issuer(GoGetSSL in our case). I'll try to find the solution for this later on!

**Comment by Zk2u** [comment]
I recommend using something that uses [Let's Encrypt](https://letsencrypt.org/docs/caa/).

**Comment by temeddix** [comment]
Hmm, it's strange that the certificate is working properly now.

![image](https://github.com/cunarist/rinf/assets/66480156/8659965b-f6c0-44d4-9c61-ebc8bb99cfc9)

Do you mind checking if the problem persists for us, @617a7a ?

**Comment by Zk2u** [comment]
Looks to be working now!

**Comment by temeddix** [comment]
Great, thank you very much for your participation!
