### ISSUE TITLE
"SmartGc memory low or critical region number, restore heap water mark"

### ISSUE THREAD

**Issue by cathino** [cunarist/rinf#252]
Hi, sometimes(NOT ALWAYS) I get a message: "SmartGc memory low or critical region number, restore heap water mark", and my code doesn't run to the end, it returns earlier than the return statement in my code.

```rust
pub async fn handle_audio_samples(rust_request: RustRequest) -> RustResponse {
    use crate::messages::audio_samples::{ReadRequest, ReadResponse};

    match rust_request.operation {
        RustOperation::Create => RustResponse::default(),
        RustOperation::Read => { 
            /* some code here */ 
            /* return something  here */ 
        }
    }
}
```

The value of **successful** is false, just like **RustResponse::default()**.
Can I have any way to check why this happens?
Thank you.

**Comment by temeddix** [comment]
Hi @newproplus , may I ask you which version of Rinf you are using?

**Comment by cathino** [comment]
@temeddix 

rinf version is 4.20.0

`flutter doctor` 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on Debian GNU/Linux 12 (bookworm) 6.1.0-15-amd64, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.0)
[✓] Connected device (3 available)
```

Sometimes it returns early without any error or message.

**Comment by cathino** [comment]
Is there a method to monitor the entire lifecycle? This can detect which step may have the problem. Because my project is quite complex, it is not easy to provide source code to reproduce the problem.

**Comment by temeddix** [comment]
Hi @newproplus , sorry for being late, I was busy with various things after christmas.

Do you mind telling me how many requests you are making? Do you use `requestToRust` function frequently?` if so, are there many 'failed responses' from Rust?

**Comment by temeddix** [comment]
Hello, @newproplus , Rinf version 5 released recently has a new architecture under the hood. Could you try it out and tell me if the problem persists?

**Comment by cathino** [comment]
@temeddix OK, I'll try it later. Thank you for your great job.

**Comment by temeddix** [comment]
For your information, you need to run `rinf template` once again if you're coming from Rinf 4 :)

**Comment by temeddix** [comment]
Rinf version 6 has a new communication system re-written from scratch, so this problem from version 4 shouldn't be present anymore. The wrapper became even thinner and resources are more efficiently used.

If anyone experiences such problems again with Rinf version 6, please let us know :)
