### ISSUE TITLE
Trying to tell you what to do when using old Android

### ISSUE THREAD

**Issue by rabbitson87** [cunarist/rinf#265]
If you use old Android, there are situations where you get an error because the native load does not work.

At this time, you can modify the Androidmanifest.xml file as follows.

I'm reporting that if I leave it in the document, it will help others who will experience the same experience. :)

```bash
...
<application
  android:extractNativeLibs="true"
  ...
>
...
```

**Comment by temeddix** [comment]
Hi @rabbitson87 , thank you very much for the report! Indeed, letting the users know how to solve this problem in the docs will be good. I will probably writing this in the FAQ section later on. Thanks!
