### ISSUE TITLE
Can't find the dependency 'package:build_tool/build_tool.dart'

### ISSUE THREAD

**Issue by ALEZ-DEV** [cunarist/rinf#273]
## Report

I recently update my project to the latest version of flutter and rinf, but for some reason, when I do ´flutter run´ (trying to compile only for linux) I get this simple error compile :

```bash
flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
Exception: Build process failed
```

All seems right, there is only the dependency build_tool that flutter don't detect I don't know why :

```
dart analyze
Analyzing Anime-Kanri...               0.9s

  error • build/linux/x64/debug/plugins/rinf/cargokit_build/tool/bin/build_tool_runner.dart:1:8 • Target of URI doesn't exist: 'package:build_tool/build_tool.dart'. Try creating the file referenced by the URI, or try using a URI for a file that does exist. • uri_does_not_exist
  ...

6 issues found.
```

I don't have any clue on how to fix this issue

## Steps to Reproduce

Clone my [my project](https://github.com/ALEZ-DEV/Anime-Kanri), you can try to update all the dependency and the issue in the code that come with it, after that just do `flutter run`

## System Information

OS : Fedora Linux 39 (Workstation Edition)

```
rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on Fedora Linux 39 (Workstation Edition) 6.6.9-200.fc39.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

**Comment by temeddix** [comment]
Hmm, this looks weird. All build test were passing in our repository, including `ubuntu-latest`. Could you try running `flutter clean`, `cargo clean` and try it again?

**Comment by ALEZ-DEV** [comment]
nope, always the same error message,

but why the package build_tool is missing ? Though I have the file in my cache folder, so I don't know why, even my editor show this error : 
![image](https://github.com/cunarist/rinf/assets/38623465/3d566198-ac17-4b35-a2be-93993479f30d)

**Comment by temeddix** [comment]
I will try to look into this soon on my Ubuntu machine, but honestly not sure what the cause is for now :\

**Comment by temeddix** [comment]
@ALEZ-DEV , and also Rinf version 6 is on its way with easier communication system. Perhaps you might want to wait for a little while.

- https://github.com/cunarist/rinf/discussions/268#discussioncomment-8139493

**Comment by ALEZ-DEV** [comment]
Yep, I can wait until this update, the new communication system seems better than the current one, the current one is simple to understand, but all get messy really quick, so yea I will wait until then (hoping that update will fix this issue)

**Comment by temeddix** [comment]
On my Ubuntu machine, Rinf 5.4.0 does work well with my litle app.

<img width="1680" alt="image" src="https://github.com/cunarist/rinf/assets/66480156/dd406808-2129-424d-a3fb-e84647e87308">

Hope that I can be of help, but for now, I don't know what the cause is. Please let me know if you have any updates.

**Comment by temeddix** [comment]
The user installation GitHub action is also telling us that it's working well on Ubuntu, strange..

- https://github.com/cunarist/rinf/actions/workflows/user_installation.yaml

**Comment by ALEZ-DEV** [comment]
I fix this issue, that was simply a package was missing so flutter was unable to build, there is the issue that work for me :
[[SuperContextMenus] Unable to build on Linux #257](https://github.com/superlistapp/super_native_extensions/issues/257)

If you are on Fedora 39, just install the `perl-Digest-SHA` package : 
`sudo dnf install perl-Digest-SHA`

Thank for the help !
