### ISSUE TITLE
Suggest additional serialize option

### ISSUE THREAD

**Issue by rabbitson87** [cunarist/rinf#293]
When I use message, I use serialize a lot. 

How about using the rinf message option (such as -useSerialize) to enable serde::Serialize, Deserialize?

**Comment by temeddix** [comment]
Hi @rabbitson87 , thanks for your opinion.

May I ask you why Protobuf serialization is not sufficient for you? Is it slow, or is there any other reason?

For now, if you want to use other serialization method for some messages, you can pass binary data between Dart and Rust to do that. If I've missed something, please let me know.

- https://rinf.cunarist.com/messaging/#binary-data

**Comment by rabbitson87** [comment]
I used serde to deal with rust, but I think it can be solved by using protobuf. 

I'll look for more thanks!
