### ISSUE TITLE
Nightly documented workaround does not work

### ISSUE THREAD

**Issue by brongan** [cunarist/rinf#319]
## Report

Following the instructions in https://rinf.cunarist.com/frequently-asked-questions/#how-do-i-use-nightly-rust I created the file "native/hub/cargokit.yaml" with the specified contents.

Even if I have the stable toolchain uninstalled, ```flutter run``` installs the stable toolchain.

## Steps to Reproduce

```
rinf template
flutter run
```

## System Information

```bash
rustc 1.80.0-nightly (faefc618c 2024-05-07)
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel , 3.19.6, on Arch Linux 6.8.9-zen1-2-zen, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

**Comment by temeddix** [comment]
Hi @brongan , thank you for your report :)

Looks like the current documentation only states how to use nightly Rust in release mode, not debug mode. Could you try writing the content below and try it again?

```yaml
cargo:
  debug:
    toolchain: nightly
  release:
    toolchain: nightly
````

More information about `cargokit.yaml` can be seen at the link below. FYI, Cargokit is the builder(+linker) for Rust crates that are used in various Flutter projects.

- https://github.com/irondash/cargokit/blob/main/docs/architecture.md

If the problem persists, please let me know! If this solves your problem, I will update the docs.

**Comment by brongan** [comment]
That completely makes sense and fixed my issue thanks!.
