### ISSUE TITLE
6.11.0 extension code not correctly

### ISSUE THREAD

**Issue by shmy** [cunarist/rinf#345]
<img width="441" alt="image" src="https://github.com/cunarist/rinf/assets/19339440/ec8ca932-6ed1-49d8-9ff5-02846d06c497"> 

> use // [RINF:DART-SIGNAL-BINARY]. 

> rinf: ^6.11.0

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.22.1 on channel stable at /Users/xxx/fvm/versions/3.22.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (10 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

**Comment by shmy** [comment]
https://github.com/cunarist/rinf/commit/af3985f565b6f5aaba91c76d6437d13217b6a729#r142637937

**Comment by temeddix** [comment]
Thanks again for the invaluable report. The new version is on its way and will be available in a few minutes.
