### ISSUE TITLE
How to access the file system?

### ISSUE THREAD

**Issue by thejobsmarket** [cunarist/rinf#347]
I am trying to read the directory I am in but I get permission denied (os error 13) and it seems like the file system is read only and not even browseable. Is there to provide access to some directories similar to assets in flutter?

**Comment by temeddix** [comment]
Hi @thejobsmarket :)

Are you using iOS or macOS? If so, you might need to set your Flutter app's permissions. Below disucssions might be able to help you out.

- https://github.com/cunarist/rinf/discussions/322
- https://github.com/cunarist/rinf/discussions/175
