### ISSUE TITLE
[Suggestion] Ignore all warnings from the generate rust code

### ISSUE THREAD

**Issue by EnvOut** [cunarist/rinf#384]
Hey,
While compiling the `native` module I see many warnings.
Could you please insert into generated module this line:
```Rust
#![allow(warnings, unused)]
```

**Comment by temeddix** [comment]
This problem is expected to be fixed in the next version of Rinf, which will be released in a few days. There were warnings indeed, and all those should have been fixed. I'll keep this open until we can test the next version :)

**Comment by temeddix** [comment]
I'll close this for now, if the problem persists feel free to re-open it
