### ISSUE TITLE
This does not need to generate rs to dart

### ISSUE THREAD

**Issue by 107295472** [cunarist/rinf#40]
When calling a string character, the data type must be converted once before it can be used

**Comment by temeddix** [comment]
Hi, thanks for leaving your opinion!

There were two reasons for this design decision:
- _Any_ serializable type can be converted into bytes, not only `String`, but also `JSON::Value`, `i32`, `f32`, `bool`....
- Bytes(`Vec<u8>`) can be sent to Dart without being copied in memory. That is, there would be a huge performance benefit when you are trying to send a large bytes data, such as a very big image or video frames.

Right now, the viewmodel is internally `HashMap<String, Vec<u8>>` and the data is sent to Dart without any conversion. I recommend you to write the formula field as `string` just to make sure that the serialized data was `String`.
```rust
let text = String::from("GitHub Issue");
let serialized = Serialized {
    bytes: text.as_bytes(),
    formula: String::from("string")
}
update_viewmodel("someCategory.itemAddress", serialized);
```

However, in future versions, automatic type conversion could _possibly_ be supported. If you have any more implemenation ideas, feel free to dive into the `bridge` module of Dart and Rust and leave a PR :)

**Comment by 107295472** [comment]
Thank you, now this automatic generation of dart is a bit slow, save it once and generate it once
