### ISSUE TITLE
Flutter package development is not supported by Rinf.

### ISSUE THREAD

**Issue by yuuko-1410** [cunarist/rinf#403]
### System Info
- MacBook Pro 2021 m1pro 8G+512
- rust、flutter SDK、Xcode、protoc is installed
### setups
1. flutter create ring_demo
2. cd ring_demo
3. flutter pub add rinf 
4. cargo install rinf
5. rinf template 
### problem description 
setup 5.
output：
`
Detected `protoc`, skipping auto installation.
The Dart CLI developer tool uses Google Analytics to report usage and diagnostic
data along with package dependencies, and crash reporting to send basic crash
reports. This data is used to help improve the Dart platform, Flutter framework,
and related tools.

Telemetry is not sent on the very first run. To disable reporting of telemetry,
run this terminal command:

    dart --disable-analytics

If you opt out of telemetry, an opt-out event will be sent, and then no further
information will be sent. This data is collected in accordance with the Google
Privacy Policy (https://policies.google.com/privacy).

Building package executable... 
Built rinf:rinf.
Flutter package development is not supported by Rinf.
`

**Comment by temeddix** [comment]
Rinf is solely for app development, not package development. To do something Rust-in-Dart package development, [`native_toolchain_rust`](https://pub.dev/packages/native_toolchain_rust/versions/0.1.0-dev.7) would be a good staring point.

Thanks for leaving the question :)
