### ISSUE TITLE
New improvements in Dart 3.5

### ISSUE THREAD

**Issue by ganeshrvel** [cunarist/rinf#408]
Do you think that the package could benefit from the newest version of Dart which was released yesterday? Maybe this could help in copy protobuf performance?

Blog: https://medium.com/dartlang/dart-3-5-6ca36259fa2f

> Dart native interoperability
> In Dart 3.5, we’ve made incremental improvements to support passing a pointer from Dart TypedData objects directly to FFI, avoiding having to first copy the memory from Dart to Native ([details](https://github.com/dart-lang/sdk/issues/44589)).

An interesting protobuf performance comment: https://github.com/dart-lang/sdk/issues/44589#issuecomment-1573894612

**Comment by temeddix** [comment]
At a glance, it looks like the memory copy of messages being sent from Dart to Rust is now avoidable. Applying this new method of calling native C functions would be a great task for the next Rinf release. Thank you for sharing!

Also, we are open to any kind of PR for this issue if anyone wants a faster release of this feature.

**Comment by ganeshrvel** [comment]
From your comment on performance in this link [here](https://github.com/cunarist/rinf/discussions/400#discussioncomment-10015154), how will the new change affect the performance metrics in the table below?

Your table:

| Operation and Data            | PB Serialization | Mem Copy | Details                                                      |
|-------------------------------|------------------|----------|--------------------------------------------------------------|
| Dart >> Rust (Message)        | O                | O        | Dart mallocs on heap, Rust deserializes from its slice       |
| Dart >> Rust (Raw Binary)     | X                | O        | Dart mallocs on heap, Rust copies it                         |
| Rust >> Dart (Message)        | O                | X        | Rust gives ownership, Dart deserializes from it              |
| Rust >> Dart (Raw Binary)     | X                | X        | Rust gives ownership                                         |

**Comment by temeddix** [comment]
If I understood the content that you provided correctly, the table would be like this after we make the change:

| Operation and Data            | PB Serialization | Mem Copy | Details                                                      |
|-------------------------------|------------------|----------|--------------------------------------------------------------|
| Dart >> Rust (Message)        | O                | X        | Rust deserializes from `Uint8List`       |
| Dart >> Rust (Raw Binary)     | X                | O        | Rust copies `Uint8List`                         |
| Rust >> Dart (Message)        | O                | X        | Rust gives ownership, Dart deserializes from it              |
| Rust >> Dart (Raw Binary)     | X                | X        | Rust gives ownership                                         |

'Dart >> Rust (Raw Binary)' would also benefit from reduced memory copy.

**Comment by temeddix** [comment]
With #425, leaf FFI call was implemented. Now memory copy from Dart to Rust has decreased.
