### ISSUE TITLE
Not sending message if the same message type was sent shortly

### ISSUE THREAD

**Issue by thunderstorm010** [cunarist/rinf#450]
I'm trying to send a message with a oneof inside of it:
```proto
// [RINF:RUST-SIGNAL]
message VehicleStateUpdate {
  oneof updated {
    bool arm = 1;
    VehicleMode mode = 2;
    double batteryVoltage = 3;
  }
}
```
The problem is, that I can't send two of them with short time in between.
```rust
 VehicleStateUpdate {
                updated: Some(vehicle_state_update::Updated::Mode(VehicleMode::from_mavlink(heartbeat.custom_mode).unwrap().into())),
            }.send_signal_to_dart();
            VehicleStateUpdate {
                updated: Some(vehicle_state_update::Updated::Arm(heartbeat.base_mode.contains(MavModeFlag::SAFETY_ARMED)))
            }.send_signal_to_dart();
```
This unfortunately doesn't work, only the second message could be received.
```rust
 VehicleStateUpdate {
                updated: Some(vehicle_state_update::Updated::Mode(VehicleMode::from_mavlink(heartbeat.custom_mode).unwrap().into())),
            }.send_signal_to_dart();
```
This does work, but with only one message
```rust
 VehicleStateUpdate {
                updated: Some(vehicle_state_update::Updated::Mode(VehicleMode::from_mavlink(heartbeat.custom_mode).unwrap().into())),
            }.send_signal_to_dart();
            tokio::time::sleep(Duration::from_millis(20)).await;
            VehicleStateUpdate {
                updated: Some(vehicle_state_update::Updated::Arm(heartbeat.base_mode.contains(MavModeFlag::SAFETY_ARMED)))
            }.send_signal_to_dart();
```
This does work. But why the delay? Why couldn't it be sent without interference without a delay?

## System Information

```bash
rustc --version => rustc 1.81.0 (eeb90cda1 2024-09-04)

flutter doctor =>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 22.04.5 LTS 6.8.0-40-generic, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.93.1)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

**Comment by temeddix** [comment]
Hi, do you mind sharing your Rinf version? Iirc Rinf had those kind of issues in older versions.

The issue might be still present in 7.0.0 so I think we need to check.

**Comment by thunderstorm010** [comment]
> Hi, do you mind sharing your Rinf version? Iirc Rinf had those kind of issues in older versions.
> 
> The issue might be still present in 7.0.0 so I think we need to check.

I have 6.15.0 installed

**Comment by thunderstorm010** [comment]
I have now migrated to 7.0.0. The same issue exists

**Comment by temeddix** [comment]
Looks like this link might be able to help us. I'll try to fix this when I have time.

- https://github.com/dart-lang/sdk/issues/39824

By the way, does the problem occur before you perform the first hot restart?

**Comment by thunderstorm010** [comment]
Yes, it does

**Comment by temeddix** [comment]
I was trying to find out the cause, but couldn't reproduce the issue... I'm wondering why :|

Rust:

```rust
for i in 0..10 {
    if i % 2 == 0 {
        SampleOutput {
            oneof_input: Some(sample_output::OneofInput::Age(3)),
        }
        .send_signal_to_dart();
    } else {
        SampleOutput {
            oneof_input: Some(sample_output::OneofInput::Name(
                "KEN".into(),
            )),
        }
        .send_signal_to_dart();
    }
}
```

Dart:

```dart
final stream = SampleOutput.rustSignalStream;
stream.listen((event) {
  print(event.message);
});
```

Output (Windows):

```
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
```

Output (Linux):

```
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
flutter: age: 3
flutter: name: KEN
```

**Comment by ykerit** [comment]
I encountered the same problem. I think the issue didn't reproduce with simpler message structures. The problem tends to occur when dealing with a more complex message structure.

**Comment by ykerit** [comment]
I conducted an experiment and found that message loss still occurs even with simpler message structures. I have a hypothesis: when the rate at which the Rust isolate sends messages to the Flutter main thread isolate exceeds Flutter's FPS, messages from the isolate might be discarded while Flutter is rendering. It's possible that there's no buffering in the isolate communication

**Comment by ykerit** [comment]
![image](https://github.com/user-attachments/assets/0e9daa80-503f-4973-959b-4f6f0432a124)
All messages can be received in the single handle, but some are lost after being sent to the stream and processed in the StreamBuilder. This indicates that the issue is not with the isolate communication

**Comment by temeddix** [comment]
Great inspection, thank you very much. Then maybe we'll need to look into the stream implementation on the Dart side.

**Comment by ykerit** [comment]
The actual sequence of invocations of the [builder](https://main-api.flutter.dev/flutter/widgets/StreamBuilder/builder.html) depends on the relative timing of events produced by the stream and the build rate of the Flutter pipeline, This might be the real reason. https://github.com/flutter/flutter/issues/102374
One possible fix could be to add caching on the Rust side and send messages in batches?

**Comment by temeddix** [comment]
@thunderstorm010 May I ask you if you were trying to receive messages with `StreamBuilder`? If so, some of the messages that were sent frequently than 16ms(60fps) might have been ignored.

For example, this code *can* lose some messages:

```dart
StreamBuilder(
  stream: MyMessage.rustSignalStream
  builder: (context, snapshot) {
    // Return a widget
  }
)
```

while this code does not:

```dart
MyMessage.rustSignalStream.listen((signal) {
  // Do something
  }
)

**Comment by thunderstorm010** [comment]
To be specific, I was using StreamProvider from the provider package.

**Comment by temeddix** [comment]
That actually is the expected behavior. When using `StreamProvider`, it may only process the latest message in the stream to trigger a widget rebuild on a new render frame.

From the provider package documentation:

> Its main use-case is to provide to a large number of a widget the content of a [Stream](https://api.flutter.dev/flutter/dart-core/Stream-class.html), without caring about reacting to events. A typical example would be to expose the battery level, or a Firebase query.

- https://pub.dev/documentation/provider/latest/provider/StreamProvider-class.html

To summarize, if you're using `StreamBuilder` or `StreamProvider`, which are focused on "building widgets", they might skip some messages if several arrive within duration of a single frame(typically 16 milliseconds).

To handle *all* messages from the stream, you should use the `Stream.listen` method like this:

```dart
MyMessage.rustSignalStream.listen((signal) {
  // Do something
});
```

- https://api.flutter.dev/flutter/dart-async/Stream/listen.html
