### ISSUE TITLE
Use `ffiPlugin: true`

### ISSUE THREAD

**Issue by stuartmorgan-g** [cunarist/rinf#51]
This package is currently building and shipping dead native code on every platform. If you use `ffiPlugin: true` instead of `pluginClass` those dummy native plugin implementations will no longer be necessary.

**Comment by temeddix** [comment]
Thanks! We will look into it soon. 🙂

**Comment by temeddix** [comment]
@stuartmorgan Now this package is a Flutter FFI plugin without dummy native code. Thank you for participating in this project!
