### ISSUE TITLE
Build error with `flutter run`,  but `cargo build` succeeds

### ISSUE THREAD

**Issue by bookshiyi** [cunarist/rinf#83]
Environment: macOS(Apple Silicon)

I have referenced the rust_in_flutter to my project, when I referencing the crate `gstreamer` or `slint`(just import the dependencies without anything, just like `use gstreamer` or `use slint` only),  I encountered a compilation error after command `flutter run`:

```
 Undefined symbols for architecture arm64:

......

  "_gst_value_is_fixed", referenced from:
      _$LT$glib..value..Value$u20$as$u20$gstreamer..value..GstValueExt$GT$::is_fixed::h823c60aabddfbe8f in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.15.rcgu.o)
  "_gst_value_is_subset", referenced from:
      _$LT$glib..value..Value$u20$as$u20$gstreamer..value..GstValueExt$GT$::is_subset::hf7a9bde6fcc536af in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.15.rcgu.o)
  "_gst_value_list_append_and_take_value", referenced from:
      gstreamer::value::List::append_value::he03d6a36e2e564b2 in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.5.rcgu.o)
  "_gst_value_list_get_type", referenced from:
      _$LT$gstreamer..value..List$u20$as$u20$glib..types..StaticType$GT$::static_type::hdbbfb74f464ccb2a in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.5.rcgu.o)
  "_gst_value_serialize", referenced from:
      _$LT$glib..value..Value$u20$as$u20$gstreamer..value..GstValueExt$GT$::serialize::hbab20b6f4262a66b in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.15.rcgu.o)
  "_gst_value_subtract", referenced from:
      _$LT$glib..value..Value$u20$as$u20$gstreamer..value..GstValueExt$GT$::subtract::h3f9b69692b700b18 in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.15.rcgu.o)
  "_gst_value_union", referenced from:
      _$LT$glib..value..Value$u20$as$u20$gstreamer..value..GstValueExt$GT$::union::h2f0b2cb330fa73ba in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.15.rcgu.o)
  "_gst_version", referenced from:
      gstreamer::auto::functions::version::hd679fd4c79d0ecce in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.10.rcgu.o)
  "_gst_version_string", referenced from:
      gstreamer::auto::functions::version_string::hfad9ad3288d2432c in libhub.a(gstreamer-b69ba5941324da5c.gstreamer.d8b50d9cbf89a4f6-cgu.10.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
```

But the strange thing is that when I use `cargo build` to bypass rust_in_flutter, there is **no error** reported.

ps: The crate package gstreamer and slint both support macOS of apple silicon version.

**Comment by temeddix** [comment]
Hi @bookshiyi , thanks for reporting this bug!

This seems like an issue with linking static libraries(`.a` file) to the executable binary. This framework uses https://github.com/irondash/cargokit to link Rust libraries for macOS and it seems we need some investigation. **cargokit** files are located at `./connectors/cargokit` folder of this repository.

I might be busy for a while, so please excuse me until I'm free. If you are okay, please feel free to make PR and I will be happy to review it and merge it as quick as possible.

Still, this framework should work well for other platforms :| I can confirm that this framework works well on x86 macOS.

**Comment by bookshiyi** [comment]
Hi @temeddix , thanks.

Thank you for helping me identify the approach to troubleshoot the issue.

Even though I am a beginner in Rust, I really enjoy Rust and have a strong desire to contribute code to the open-source world.

I will try to fix this bug.

**Comment by temeddix** [comment]
Happy to hear that :) Please feel free to tag me when you make a PR.

By the way, symbol issues when linking static library for macOS apps were also present in another Flutter-Rust project called `super_native_extensions`. I made [a pull request](https://github.com/superlistapp/super_native_extensions/pull/141) to that repo before, which seems to be related to this problem. `super_native_extensions` also uses `cargokit`, just like this project. Maybe this link might be a help.

**Comment by bookshiyi** [comment]
@temeddix I'd like to provide some feedback:

I followed your advice, viewed super_native_extensions's [PR](https://github.com/superlistapp/super_native_extensions/pull/141) mentioned `.podspec`  changes:
`OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/libhub.a`
`OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/libhub.a -framework CoreServices`

After command `flutter run -v`, the libhub.a file has been generated and it's file path is correct.

This is some log of `flutter run -v`:
```
export OTHER_LDFLAGS\=\ -force_load\  /Users/USERNAME/repos/MYPROJECT/build/macos/Build/Products/Debug/rust_in_flutter/libhub.a
```

I tried using `-force_load`, `-all_load`,  `-l`, but it seems to have little effect.

----

However, I have made some new discoveries:

*  target/debug/libhub.a
  
  The `target/debug/libhub.a` file that built by command `cargo build`, when I use command 
`ar -t target/debug/libhub.a` to inspect it,
 I have got a lot of messages that `.o` files has been compiled in this `.a` lib file, here are some of the rusult:
  ```
  once_cell-11185762ce73204a.once_cell.6731a559064eefbc-cgu.9.rcgu.o
  bitflags-3f6b34c3afc19730.bitflags.ae1711ba5b25353a-cgu.0.rcgu.o
  bitflags-3f6b34c3afc19730.bitflags.ae1711ba5b25353a-cgu.1.rcgu.o
  bitflags-3f6b34c3afc19730.bitflags.ae1711ba5b25353a-cgu.2.rcgu.o
  bitflags-3f6b34c3afc19730.bitflags.ae1711ba5b25353a-cgu.3.rcgu.o
  bitflags-3f6b34c3afc19730.bitflags.ae1711ba5b25353a-cgu.4.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.0.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.1.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.10.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.11.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.12.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.2.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.3.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.4.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.5.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.6.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.7.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.8.rcgu.o
  gstreamer_sys-cc6e64f60f76625c.gstreamer_sys.4b52fb123b01391e-cgu.9.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.0.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.1.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.10.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.11.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.2.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.3.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.4.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.5.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.6.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.7.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.8.rcgu.o
  gobject_sys-a90e106e7eaef946.gobject_sys.4fd6e84bc28f226d-cgu.9.rcgu.o
  glib_sys-fc580655124209bb.glib_sys.7d265415d2c044a9-cgu.0.rcgu.o
  ```

* build/macos/Build/Products/Debug/rust_in_flutter/libhub.a
  
  The `build/macos/Build/Products/Debug/rust_in_flutter/libhub.a` file that built by **rust_in_flutter**  and **cargo_kit**  when I run command `flutter run`, when I use command `ar -t build/macos/Build/Products/Debug/rust_in_flutter/libhub.a` to inspect it, I have got these:
  
  ```
  ar: build/macos/Build/Products/Debug/rust_in_flutter/libhub.a is a fat file (use libtool(1) or lipo(1) and ar(1) on it)
  ar: build/macos/Build/Products/Debug/rust_in_flutter/libhub.a: Inappropriate file type or format
  ```

**Comment by temeddix** [comment]
This is a really valuable inspection! Though we don't know what the problem is, we now know things that are NOT problems.

In addition, may I ask you to check if you are able to run the example Rust-In-Flutter app, located at `./example` directory of this repository? I would like to do this myself, but I don't have a M1 mac 👀.

**Comment by bookshiyi** [comment]
Additional:

```
$ lipo -info  build/macos/Build/Products/Debug/rust_in_flutter/libhub.a
Architectures in the fat file: build/macos/Build/Products/Debug/rust_in_flutter/libhub.a are: arm64 

$ lipo -info target/debug/libhub.a 
Non-fat file: target/debug/libhub.a is architecture: arm64
```

**Comment by bookshiyi** [comment]
> This is a really valuable inspection! Though we don't know what the problem is, we now know things that are NOT problems.
> 
> In addition, may I ask you to check if you are able to run the example Rust-In-Flutter app, located at `./example` directory of this repository? I would like to do this myself, but I don't have a M1 mac 👀.

This repository's example works very well on apple silicon macOS. It is a beautiful work!

And I have tried to add  some common packages without any problems. 
At present, I only found that when gstreamer or slint are added to my project, the correct `.a` files cannot be generated.

btw: I feel like we are getting closer to the truth too ,hahaha

**Comment by bookshiyi** [comment]
When gstreamer-rs and the latest version of purely_cargokit branch as dependencies to compile the flutter project , it actually passed.
There will be a more in-depth test tomorrow, which seems to be good news, although it may be brought about by the Dart sdk upgrade.

**Comment by temeddix** [comment]
Wow, that's a good news. So it had to be something related to corrosion.

**Comment by bookshiyi** [comment]
> Wow, that's a good news. So it had to be something related to corrosion.

Although I hope it is the result of my work, it seems that before it is separated from corrosion, the compilation of macOS target is the depend on cargokit.https://github.com/cunarist/rust-in-flutter/issues/95#issuecomment-1678592536.

@temeddix Is my understanding correct?

**Comment by temeddix** [comment]
Oh I see, you were using macOS. I just thought like you were using Windows. That's mysterious...

**Comment by bookshiyi** [comment]
> When gstreamer-rs and the latest version of purely_cargokit branch as dependencies to compile the flutter project , it actually passed.
> There will be a more in-depth test tomorrow, which seems to be good news, although it may be brought about by the Dart sdk upgrade.

It seems to be a misunderstanding.When gstreamer-rs is really integrated, the problem is the same as before.

**Comment by bookshiyi** [comment]
```rust
     let perform_lipo = |target_file: &Path, lib_name: &str| -> Result<()> {
        let mut cmd = Command::new("lipo");
        cmd.arg("-create");
        for arch in &archs {
            let path = lib_path(lib_name, arch)?;
            cmd.arg(path);
        }
        cmd.arg("-output");
        cmd.arg(target_file);
        run_command(cmd)?;
        Ok(())
    };
```
(https://github.com/irondash/cargokit/blob/54ae0380f0d85c31733b4e3f4bd34fbfb7003a35/build_tool/src/build_pod.rs#L107-L118)
     

```rust
    if is_static_lib {
        let target_file = final_target_dir()?.join(&static_lib_name);
        perform_lipo(&target_file, &static_lib_name)?;
        Ok(())
    } else {
        let bundle_paths = &[
            format!("{}.framework/Versions/A/{}", lib_name, lib_name),
            format!("{}.framework/{}", lib_name, lib_name), // iOS
        ];

        // Dynamic library in a bundle. Replace bundle dylib with lipoed rust dylib.
        for bundle_path in bundle_paths {
            let target_file = final_target_dir()?.join(bundle_path);
            if target_file.exists() {
                let lib_name = format!("lib{}.dylib", lib_name);
                perform_lipo(&target_file, &lib_name)?;

                // Replace absolute id with @rpath one so that it works properly
                // when moved to Frameworks.
                let mut cmd = Command::new("install_name_tool");
                cmd.arg("-id");
                cmd.arg(format!("@rpath/{}", bundle_path));
                cmd.arg(&target_file);
                run_command(cmd)?;
                return Ok(());
            }
        }
        Err(anyhow::anyhow!("Unable to find bundle for dynamic library"))
    }
}
``` 

https://github.com/irondash/cargokit/blob/54ae0380f0d85c31733b4e3f4bd34fbfb7003a35/build_tool/src/build_pod.rs#L129-L158

It seems that the problem is located here.

When only running the `cargo build` command on arm version of macOS, `libhua.a` is a only arm64 version.

However, when compiling with `cargokit` on the arm version of macOS, the value of `arche` is `[arm64,x86_64]`, 
so `build_pos.rs` will use `lipo` command to merge the target files of the arm64 and x86_64 into `libhub.a`.

**Comment by bookshiyi** [comment]
Some new understandings(Apple silicon macOS):

1. The `libhub.a` file generated using `cargo build` is of `non-fat` type

2. The `libhub.a` file generated using `cargokit` is of `fat` type

3. Cocoapads have supported automaticly adapt non-fat or fat to link to target already.

In my project:
As long as I integrate gstreamer-rs, even if I modify the `lipo` function of `build_pods` in `cargokit`, forcing the `libhub.a` file to be of `fat` type, `libhub.a` although couldn't be linked to flutter app.

In example of rust-in-flutter:
The `libhub.a` file generated by cartkit  is also `fat` type, but it although cloud be linked to flutter app and run well.



So, whether the file is fat or non-fat should not be the point.

**Comment by temeddix** [comment]
By the way, does this problem persist? @bookshiyi

**Comment by bookshiyi** [comment]
> By the way, does this problem persist? @bookshiyi

Unfortunately, this problem still exists.

**Comment by temeddix** [comment]
At least I can find what they have in common. They depend on external C code.

- Slint: skia, openGL
- Gstreamer: C Gstreamer

The fact that they are not pure Rust crates might be related to this error. If we solve this problem, any other crates that depend on C code will be able to work properly as well.

Do you mind sharing your project's code so that we can examine it together?

**Comment by temeddix** [comment]
- https://stackoverflow.com/questions/5352113/how-do-i-turn-a-fat-library-into-a-non-fat-library

Hmm, I have a feeling that we will need to make PRs at cargokit repository directly.

**Comment by bookshiyi** [comment]
> * https://stackoverflow.com/questions/5352113/how-do-i-turn-a-fat-library-into-a-non-fat-library
> 
> Hmm, I have a feeling that we will need to make PRs at cargokit repository directly.


Although we could generate non-fat `libhub.a`  library by modify cargokit (related lipo command), but the generated non-fat `libhub.a` still wouldn't be called right.

Related code(`lipo` command): 
https://github.com/irondash/cargokit/blob/7a5bba8eefbfe7e567f754477fd172e7a06b153f/build_tool/lib/src/build_pod.dart#L33-L40

**Comment by bookshiyi** [comment]
> At least I can find what they have in common. They depend on external C code.
> 
> * Slint: skia, openGL
> * Gstreamer: C Gstreamer
> 
> The fact that they are not pure Rust crates might be related to this error. If we solve this problem, any other crates that depend on C code will be able to work properly as well.
> 
> Do you mind sharing your project's code so that we can examine it together?

Great, maybe it is a important discovery that slint and gstreamer are non-purely rust crate.

I haven't built a complex project yet, but in my experience, minimal method to reproduce the bug just only need:

1. Add `gstreamer` dependency to the `Cargo.toml`
2. Add `use gstreamer;` to `native/src/lib.rs`

**Comment by temeddix** [comment]
https://github.com/cunarist/rust-in-flutter/issues/110#issuecomment-1691346024

It feels like this issue might be somehow related to this one, though I'm not sure. Because it also had to to `lipo` things and manually copy-paste `libhub.a` file.

**Comment by temeddix** [comment]
At least `slint` works well :)

**Comment by temeddix** [comment]
I was able to make `machineid-rs` work in the `enable-other-crates` branch. I had to add a system header file to the `macos` folder of RIF. However, this cannot be a general solution because users need to be able to modify their own project, not RIF.

I thought about asking users to create their own Flutter FFI plugin in the docs, but that would be too much when simply trying to add header files to the binary.

**Comment by temeddix** [comment]
Hopefully, this should have been fixed in 4.5.0, but because `gstreamer-rs` is not a system library, I think you might need to include C headers manually from the `.xcodeproj` file.

<img width="1278" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/74170d07-91ac-4c18-9bcd-01ad6f34fdd0">

<img width="1680" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/810b84e1-eb72-46a7-84e6-72cc583fbfe0">

I didn't inspect deeper into this step, so please share your progress if you have anything new :)

**Comment by temeddix** [comment]
Or, perhaps using `cc` crate with `native/hub/build.rs` can be an answer. Just another possibility 👀

**Comment by bookshiyi** [comment]
Thank for you resolved the deeply hidden bug.

Your expertise and dedication in finding and fixing this bug have been greatly appreciated.

**Comment by temeddix** [comment]
No problem, may I accept that as the bug is completely fixed? Were there no additional steps involved?

**Comment by temeddix** [comment]
@bookshiyi

**Comment by temeddix** [comment]
Closing this assuming that it has been solved with recent updates, but please continue the conversation if anyone confronts this issue again :)
