### ISSUE TITLE
A small warning related to `tar.exe` appears in the CI

### ISSUE THREAD

**Issue by temeddix** [cunarist/rinf#93]
<img width="568" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/3120810f-7f64-437b-8e40-047c9d30b148">

**Comment by bookshiyi** [comment]
> <img alt="image" width="568" src="https://user-images.githubusercontent.com/66480156/260632775-3120810f-7f64-437b-8e40-047c9d30b148.png">

Yes, It seems to indicate that a certain cache program cannot be packaged on the Windows platform.

**Comment by temeddix** [comment]
Yeah it seems so, though it's not as urgent as other issues :)
